services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: doc_user
      POSTGRES_PASSWORD: strictpassword
      POSTGRES_DB: docs_db
    volumes:
      - pg_doc_data:/var/lib/postgresql/pg_doc_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doc_user -d docs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: doc_user
      POSTGRES_PASSWORD: strictpassword
      POSTGRES_DB: docs_test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doc_user -d docs_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
  
  redis-test:
    image: redis:7-alpine
  
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          ignore:
            - .env

    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      postgres-test:
        condition: service_healthy

volumes:
  pg_doc_data: